# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.6.0'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: $(TF_VERSION)

# ✅ Authenticate to Azure using the service connection
- task: AzureCLI@2
  inputs:
    azureSubscription: 'e3d7bd63-60f7-4a78-921f-c70964b5b534'  # Replace with your actual service connection name if necessary
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Init and apply
      terraform init
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)